spring:
  security:
    oauth2:
      authorizationserver:
        endpoint:
          jwk-set-uri: ${jwk-set-uri:http://localhost:8080/oauth2/keys}
  application:
    name: springboot-test
    messages:
      basicGreetMessage: Hello, There!
    order-service:
      host: http://localhost:9090
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springboot-test
    username: postgres
    password: postgres


